name: UelhIldian
version: '1.0-SNAPSHOT'
main: valorium.uelhildian.UelhIldian
api-version: '1.21'
author: Valorium
description: Système de Bilhetas Ildians pour Minecraft

commands:
  bilheta:
    description: Gère le système de bilhetas Ildians
    usage: /bilheta <setbouton|info|reload>
    permission: uelh.bilheta.admin
    aliases: [bilhetas, blt]

permissions:
  uelh.bilheta.admin:
    description: Permet de gérer le système de bilhetas
    default: op
