name: UelhIldian
version: '1.0-SNAPSHOT'
main: valorium.uelhildian.UelhIldian
api-version: '1.21'
author: Valorium
description: Plugin Uèlh Ildian avec client API
website: https://valorium-mc.fr

commands:
  uelh:
    description: Commande principale du plugin
    usage: /uelh
    permission: uelhildian.use
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande"

permissions:
  uelhildian.use:
    description: Permet d'utiliser les commandes du plugin
    default: true

